#include "ItemIdMaps.hpp"
#include "036_MapA5.hpp"
#include "gz.hpp"

#include <Item/Item.hpp>
#include <Player/PlayerGet.hpp>
#include <Save/AdventureFlags.hpp>
#include <types.h>

u32 gGetItemMap[] = {
    GIModel_None, // ItemId_Nothing
    GIModel_shdA, // ItemId_NormalShield
    GIModel_swdA, // ItemId_NormalSword
    GIModel_trnd, // ItemId_Whirlwind
    GIModel_bomb, // ItemId_BombBag
    GIModel_bowA, // ItemId_NormalBow
    GIModel_bmrn, // ItemId_Boomerang
    GIModel_whip, // ItemId_Whip
    GIModel_srod, // ItemId_SandRod
    GIModel_None, // ItemId_9
    GIModel_keyN, // ItemId_NormalKey
    GIModel_keyB, // ItemId_BossKey
    GIModel_rupG, // ItemId_GreenRupee
    GIModel_rupB, // ItemId_BlueRupee
    GIModel_rupR, // ItemId_RedRupee
    GIModel_rupG, // ItemId_BigGreenRupee
    GIModel_rupR, // ItemId_BigRedRupee
    GIModel_rupL, // ItemId_BigGoldRupee
    GIModel_frcY, // ItemId_ForceGem_18
    GIModel_frcY, // ItemId_ForceGem_19
    GIModel_frcY, // ItemId_ForceGem_20
    GIModel_litA, // ItemId_ForestGlyph
    GIModel_litB, // ItemId_SnowGlyph
    GIModel_litC, // ItemId_OceanGlyph
    GIModel_litD, // ItemId_FireGlyph
    GIModel_litA, // ItemId_25
    GIModel_litB, // ItemId_26
    GIModel_litC, // ItemId_27
    GIModel_litD, // ItemId_28
    GIModel_litC, // ItemId_29
    GIModel_litA, // ItemId_FinalTrack
    GIModel_None, // ItemId_31
    GIModel_None, // ItemId_32
    GIModel_None, // ItemId_33
    GIModel_None, // ItemId_34
    GIModel_frcY, // ItemId_ForceGem_35
    GIModel_frcY, // ItemId_ForceGem_36
    GIModel_frcY, // ItemId_ForceGem_37
    GIModel_cloA, // ItemId_RecruitUniform
    GIModel_ptmL, // ItemId_PostmasterLetter
    GIModel_hrtu, // ItemId_HeartContainer
    GIModel_apdM, // ItemId_QuiverMedium
    GIModel_bmbM, // ItemId_BombBagMedium
    GIModel_frcY, // ItemId_ForceGem_43
    GIModel_frcY, // ItemId_ForceGem_44
    GIModel_frcY, // ItemId_ForceGem_45
    GIModel_frcY, // ItemId_ForceGem_46
    GIModel_frcY, // ItemId_ForceGem_47
    GIModel_frcY, // ItemId_ForceGem_48
    GIModel_frcY, // ItemId_ForceGem_49
    GIModel_frcY, // ItemId_ForceGem_50
    GIModel_frcY, // ItemId_ForceGem_51
    GIModel_frcY, // ItemId_ForceGem_52
    GIModel_frcY, // ItemId_ForceGem_53
    GIModel_frcY, // ItemId_ForceGem_54
    GIModel_frcY, // ItemId_ForceGem_55
    GIModel_frcY, // ItemId_ForceGem_56
    GIModel_frcY, // ItemId_ForceGem_57
    GIModel_frcY, // ItemId_ForceGem_58
    GIModel_frcY, // ItemId_ForceGem_59
    GIModel_frcY, // ItemId_ForceGem_60
    GIModel_frcY, // ItemId_ForceGem_61
    GIModel_pflt, // ItemId_PanFlute
    GIModel_stmp, // ItemId_StampBook
    GIModel_bowB, // ItemId_LightBow
    GIModel_swdB, // ItemId_LokomoSword
    GIModel_przC, // ItemId_TenPriceCard
    GIModel_revR, // ItemId_RedPotion
    GIModel_revP, // ItemId_PurplePotion
    GIModel_revY, // ItemId_YellowPotion
    GIModel_mons, // ItemId_DemonFossil
    GIModel_stlb, // ItemId_StalfosSkull
    GIModel_star, // ItemId_StarFragment
    GIModel_beee, // ItemId_BeeLarvae
    GIModel_mrrn, // ItemId_WoodHeart
    GIModel_prlB, // ItemId_DarkPearlLoop
    GIModel_prlA, // ItemId_WhitePearlLoop
    GIModel_crwn, // ItemId_RutoCrown
    GIModel_zola, // ItemId_DragonScale
    GIModel_pnec, // ItemId_PirateNecklace
    GIModel_bowl, // ItemId_PalaceDish
    GIModel_glon, // ItemId_GoronAmber
    GIModel_jade, // ItemId_MysticJade
    GIModel_coin, // ItemId_AncientCoin
    GIModel_gold, // ItemId_PricelessStone
    GIModel_ring, // ItemId_RegalRing
    GIModel_arst, // ItemId_ArrowsRefill
    GIModel_bmst, // ItemId_BombsRefill
    GIModel_sold, // ItemId_SoldOutSign
    GIModel_shdB, // ItemId_AncientShield
    GIModel_apdL, // ItemId_QuiverLarge
    GIModel_bmbL, // ItemId_BombBagLarge
    GIModel_None, // ItemId_RandCommonTreasure
    GIModel_None, // ItemId_RandUncommonTreasure
    GIModel_None, // ItemId_RandRareTreasure
    GIModel_None, // ItemId_RandLegendaryTreasure
    GIModel_szku, // ItemId_TearLight
    GIModel_Lcmp, // ItemId_LightCompass
    GIModel_makA, // ItemId_ScrollSpinAttack
    GIModel_makB, // ItemId_ScrollBeam
    GIModel_ptmL, // ItemId_LinebeckLetter
    GIModel_gdpf, // ItemId_PanFluteSong_101
    GIModel_gdpf, // ItemId_PanFluteSong_102
    GIModel_gdpf, // ItemId_PanFluteSong_103
    GIModel_gdpf, // ItemId_PanFluteSong_104
    GIModel_gdpf, // ItemId_PanFluteSong_105
    GIModel_rbnt, // ItemId_RabbitNet
    GIModel_poit, // ItemId_BeedleCard
    GIModel_poiS, // ItemId_SilverCard
    GIModel_poiG, // ItemId_GoldCard
    GIModel_poiP, // ItemId_PlatinumCard
    GIModel_poiD, // ItemId_DiamondCard
    GIModel_poiF, // ItemId_FreebieCard
    GIModel_poi5, // ItemId_QuintupleCard
    GIModel_ptmL, // ItemId_CarbenLetter
    GIModel_cloA, // ItemId_RecruitUniform2
    GIModel_cloB, // ItemId_EngineerUniform

    GIModel_szku, // ExtraItemId_TearLight_1
    GIModel_szku, // ExtraItemId_TearLight_2
    GIModel_szku, // ExtraItemId_TearLight_3
    GIModel_szku, // ExtraItemId_TearLight_4
    GIModel_szku, // ExtraItemId_TearLight_5
    GIModel_keyN, // ExtraItemId_NormalKey_2
    GIModel_keyN, // ExtraItemId_NormalKey_4
    GIModel_keyN, // ExtraItemId_NormalKey_5
    GIModel_keyN, // ExtraItemId_NormalKey_6
    GIModel_keyN, // ExtraItemId_NormalKey_Tunnel
    GIModel_keyN, // ExtraItemId_NormalKey_Wooded
    GIModel_keyN, // ExtraItemId_NormalKey_Blizzard
    GIModel_keyN, // ExtraItemId_NormalKey_Marine
    GIModel_keyN, // ExtraItemId_NormalKey_Mountain
    GIModel_keyN, // ExtraItemId_NormalKey_Desert
};

// BMG IDs
u32 gBMGMap[] = {
    MSG(ItemId_Nothing), // ItemId_Nothing
    MSG(ItemId_NormalShield), // ItemId_NormalShield
    MSG(ItemId_NormalSword), // ItemId_NormalSword
    MSG(ItemId_Whirlwind), // ItemId_Whirlwind
    MSG(ItemId_BombBag), // ItemId_BombBag
    MSG(ItemId_NormalBow), // ItemId_NormalBow
    MSG(ItemId_Boomerang), // ItemId_Boomerang
    MSG(ItemId_Whip), // ItemId_Whip
    MSG(ItemId_SandRod), // ItemId_SandRod
    MSG(ItemId_9), // ItemId_9
    MSG(ItemId_NormalKey), // ItemId_NormalKey
    MSG(ItemId_BossKey), // ItemId_BossKey
    MSG(ItemId_GreenRupee), // ItemId_GreenRupee
    MSG(ItemId_BlueRupee), // ItemId_BlueRupee
    MSG(ItemId_RedRupee), // ItemId_RedRupee
    MSG(ItemId_BigGreenRupee), // ItemId_BigGreenRupee
    MSG(ItemId_BigRedRupee), // ItemId_BigRedRupee
    MSG(ItemId_BigGoldRupee), // ItemId_BigGoldRupee
    MSG(ItemId_ForceGem_18), // ItemId_ForceGem_18
    MSG(ItemId_ForceGem_19), // ItemId_ForceGem_19
    MSG(ItemId_ForceGem_20), // ItemId_ForceGem_20
    MSG(ItemId_ForestGlyph), // ItemId_ForestGlyph
    MSG(ItemId_SnowGlyph), // ItemId_SnowGlyph
    MSG(ItemId_OceanGlyph), // ItemId_OceanGlyph
    MSG(ItemId_FireGlyph), // ItemId_FireGlyph
    MSG(ItemId_25), // ItemId_25
    MSG(ItemId_26), // ItemId_26
    MSG(ItemId_27), // ItemId_27
    MSG(ItemId_28), // ItemId_28
    MSG(ItemId_29), // ItemId_29
    MSG(ItemId_FinalTrack), // ItemId_FinalTrack
    MSG(ItemId_31), // ItemId_31
    MSG(ItemId_32), // ItemId_32
    MSG(ItemId_33), // ItemId_33
    MSG(ItemId_34), // ItemId_34
    MSG(ItemId_ForceGem_35), // ItemId_ForceGem_35
    MSG(ItemId_ForceGem_36), // ItemId_ForceGem_36
    MSG(ItemId_ForceGem_37), // ItemId_ForceGem_37
    MSG(ItemId_RecruitUniform), // ItemId_RecruitUniform
    MSG(ItemId_PostmasterLetter), // ItemId_PostmasterLetter
    MSG(ItemId_HeartContainer), // ItemId_HeartContainer
    MSG(ItemId_QuiverMedium), // ItemId_QuiverMedium
    MSG(ItemId_BombBagMedium), // ItemId_BombBagMedium
    MSG(ItemId_ForceGem_43), // ItemId_ForceGem_43
    MSG(ItemId_ForceGem_44), // ItemId_ForceGem_44
    MSG(ItemId_ForceGem_45), // ItemId_ForceGem_45
    MSG(ItemId_ForceGem_46), // ItemId_ForceGem_46
    MSG(ItemId_ForceGem_47), // ItemId_ForceGem_47
    MSG(ItemId_ForceGem_48), // ItemId_ForceGem_48
    MSG(ItemId_ForceGem_49), // ItemId_ForceGem_49
    MSG(ItemId_ForceGem_50), // ItemId_ForceGem_50
    MSG(ItemId_ForceGem_51), // ItemId_ForceGem_51
    MSG(ItemId_ForceGem_52), // ItemId_ForceGem_52
    MSG(ItemId_ForceGem_53), // ItemId_ForceGem_53
    MSG(ItemId_ForceGem_54), // ItemId_ForceGem_54
    MSG(ItemId_ForceGem_55), // ItemId_ForceGem_55
    MSG(ItemId_ForceGem_56), // ItemId_ForceGem_56
    MSG(ItemId_ForceGem_57), // ItemId_ForceGem_57
    MSG(ItemId_ForceGem_58), // ItemId_ForceGem_58
    MSG(ItemId_ForceGem_59), // ItemId_ForceGem_59
    MSG(ItemId_ForceGem_60), // ItemId_ForceGem_60
    MSG(ItemId_ForceGem_61), // ItemId_ForceGem_61
    MSG(ItemId_PanFlute), // ItemId_PanFlute
    MSG(ItemId_StampBook), // ItemId_StampBook
    MSG(ItemId_LightBow), // ItemId_LightBow
    MSG(ItemId_LokomoSword), // ItemId_LokomoSword
    MSG(ItemId_TenPriceCard), // ItemId_TenPriceCard
    MSG(ItemId_RedPotion), // ItemId_RedPotion
    MSG(ItemId_PurplePotion), // ItemId_PurplePotion
    MSG(ItemId_YellowPotion), // ItemId_YellowPotion
    MSG(ItemId_DemonFossil), // ItemId_DemonFossil
    MSG(ItemId_StalfosSkull), // ItemId_StalfosSkull
    MSG(ItemId_StarFragment), // ItemId_StarFragment
    MSG(ItemId_BeeLarvae), // ItemId_BeeLarvae
    MSG(ItemId_WoodHeart), // ItemId_WoodHeart
    MSG(ItemId_DarkPearlLoop), // ItemId_DarkPearlLoop
    MSG(ItemId_WhitePearlLoop), // ItemId_WhitePearlLoop
    MSG(ItemId_RutoCrown), // ItemId_RutoCrown
    MSG(ItemId_DragonScale), // ItemId_DragonScale
    MSG(ItemId_PirateNecklace), // ItemId_PirateNecklace
    MSG(ItemId_PalaceDish), // ItemId_PalaceDish
    MSG(ItemId_GoronAmber), // ItemId_GoronAmber
    MSG(ItemId_MysticJade), // ItemId_MysticJade
    MSG(ItemId_AncientCoin), // ItemId_AncientCoin
    MSG(ItemId_PricelessStone), // ItemId_PricelessStone
    MSG(ItemId_RegalRing), // ItemId_RegalRing
    MSG(ItemId_ArrowsRefill), // ItemId_ArrowsRefill
    MSG(ItemId_BombsRefill), // ItemId_BombsRefill
    MSG(ItemId_SoldOutSign), // ItemId_SoldOutSign
    MSG(ItemId_AncientShield), // ItemId_AncientShield
    MSG(ItemId_QuiverLarge), // ItemId_QuiverLarge
    MSG(ItemId_BombBagLarge), // ItemId_BombBagLarge
    MSG(ItemId_RandCommonTreasure), // ItemId_RandCommonTreasure
    MSG(ItemId_RandUncommonTreasure), // ItemId_RandUncommonTreasure
    MSG(ItemId_RandRareTreasure), // ItemId_RandRareTreasure
    MSG(ItemId_RandLegendaryTreasure), // ItemId_RandLegendaryTreasure
    MSG(ItemId_TearLight), // ItemId_TearLight
    MSG(ItemId_LightCompass), // ItemId_LightCompass
    MSG(ItemId_ScrollSpinAttack), // ItemId_ScrollSpinAttack
    MSG(ItemId_ScrollBeam), // ItemId_ScrollBeam
    MSG(ItemId_LinebeckLetter), // ItemId_LinebeckLetter
    MSG(ItemId_PanFluteSong_101), // ItemId_PanFluteSong_101
    MSG(ItemId_PanFluteSong_102), // ItemId_PanFluteSong_102
    MSG(ItemId_PanFluteSong_103), // ItemId_PanFluteSong_103
    MSG(ItemId_PanFluteSong_104), // ItemId_PanFluteSong_104
    MSG(ItemId_PanFluteSong_105), // ItemId_PanFluteSong_105
    MSG(ItemId_RabbitNet), // ItemId_RabbitNet
    MSG(ItemId_BeedleCard), // ItemId_BeedleCard
    MSG(ItemId_SilverCard), // ItemId_SilverCard
    MSG(ItemId_GoldCard), // ItemId_GoldCard
    MSG(ItemId_PlatinumCard), // ItemId_PlatinumCard
    MSG(ItemId_DiamondCard), // ItemId_DiamondCard
    MSG(ItemId_FreebieCard), // ItemId_FreebieCard
    MSG(ItemId_QuintupleCard), // ItemId_QuintupleCard
    MSG(ItemId_CarbenLetter), // ItemId_CarbenLetter
    MSG(ItemId_RecruitUniform2), // ItemId_RecruitUniform2
    MSG(ItemId_EngineerUniform), // ItemId_EngineerUniform

    MSG(ExtraItemId_TearLight_1), // ExtraItemId_TearLight_1
    MSG(ExtraItemId_TearLight_2), // ExtraItemId_TearLight_2
    MSG(ExtraItemId_TearLight_3), // ExtraItemId_TearLight_3
    MSG(ExtraItemId_TearLight_4), // ExtraItemId_TearLight_4
    MSG(ExtraItemId_TearLight_5), // ExtraItemId_TearLight_5
    MSG(ExtraItemId_NormalKey_2), // ExtraItemId_NormalKey_2
    MSG(ExtraItemId_NormalKey_4), // ExtraItemId_NormalKey_4
    MSG(ExtraItemId_NormalKey_5), // ExtraItemId_NormalKey_5
    MSG(ExtraItemId_NormalKey_6), // ExtraItemId_NormalKey_6
    MSG(ExtraItemId_NormalKey_Tunnel), // ExtraItemId_NormalKey_Tunnel
    MSG(ExtraItemId_NormalKey_Wooded), // ExtraItemId_NormalKey_Wooded
    MSG(ExtraItemId_NormalKey_Blizzard), // ExtraItemId_NormalKey_Blizzard
    MSG(ExtraItemId_NormalKey_Marine), // ExtraItemId_NormalKey_Marine
    MSG(ExtraItemId_NormalKey_Mountain), // ExtraItemId_NormalKey_Mountain
    MSG(ExtraItemId_NormalKey_Desert), // ExtraItemId_NormalKey_Desert
};

//! TODO: this should also be used by PlayerGet
u16 gShopAdvFlagMap[] = {
    RandoAdventureFlag_BoughtNothing, // ItemId_Nothing
    RandoAdventureFlag_BoughtNormalShield, // ItemId_NormalShield
    RandoAdventureFlag_BoughtNormalSword, // ItemId_NormalSword
    RandoAdventureFlag_BoughtWhirlwind, // ItemId_Whirlwind
    RandoAdventureFlag_BoughtBombBag, // ItemId_BombBag
    RandoAdventureFlag_BoughtNormalBow, // ItemId_NormalBow
    RandoAdventureFlag_BoughtBoomerang, // ItemId_Boomerang
    RandoAdventureFlag_BoughtWhip, // ItemId_Whip
    RandoAdventureFlag_BoughtSandRod, // ItemId_SandRod
    RandoAdventureFlag_Bought9, // ItemId_9
    RandoAdventureFlag_BoughtNormalKey, // ItemId_NormalKey
    RandoAdventureFlag_BoughtBossKey, // ItemId_BossKey
    RandoAdventureFlag_BoughtGreenRupee, // ItemId_GreenRupee
    RandoAdventureFlag_BoughtBlueRupee, // ItemId_BlueRupee
    RandoAdventureFlag_BoughtRedRupee, // ItemId_RedRupee
    RandoAdventureFlag_BoughtBigGreenRupee, // ItemId_BigGreenRupee
    RandoAdventureFlag_BoughtBigRedRupee, // ItemId_BigRedRupee
    RandoAdventureFlag_BoughtBigGoldRupee, // ItemId_BigGoldRupee
    RandoAdventureFlag_BoughtForceGem_18, // ItemId_ForceGem_18
    RandoAdventureFlag_BoughtForceGem_19, // ItemId_ForceGem_19
    RandoAdventureFlag_BoughtForceGem_20, // ItemId_ForceGem_20
    RandoAdventureFlag_BoughtForestGlyph, // ItemId_ForestGlyph
    RandoAdventureFlag_BoughtSnowGlyph, // ItemId_SnowGlyph
    RandoAdventureFlag_BoughtOceanGlyph, // ItemId_OceanGlyph
    RandoAdventureFlag_BoughtFireGlyph, // ItemId_FireGlyph
    RandoAdventureFlag_Bought25, // ItemId_25
    RandoAdventureFlag_Bought26, // ItemId_26
    RandoAdventureFlag_Bought27, // ItemId_27
    RandoAdventureFlag_Bought28, // ItemId_28
    RandoAdventureFlag_Bought29, // ItemId_29
    RandoAdventureFlag_BoughtFinalTrack, // ItemId_FinalTrack
    RandoAdventureFlag_Bought31, // ItemId_31
    RandoAdventureFlag_Bought32, // ItemId_32
    RandoAdventureFlag_Bought33, // ItemId_33
    RandoAdventureFlag_Bought34, // ItemId_34
    RandoAdventureFlag_BoughtForceGem_35, // ItemId_ForceGem_35
    RandoAdventureFlag_BoughtForceGem_36, // ItemId_ForceGem_36
    RandoAdventureFlag_BoughtForceGem_37, // ItemId_ForceGem_37
    RandoAdventureFlag_BoughtRecruitUniform, // ItemId_RecruitUniform
    RandoAdventureFlag_BoughtPostmasterLetter, // ItemId_PostmasterLetter
    RandoAdventureFlag_BoughtHeartContainer, // ItemId_HeartContainer
    RandoAdventureFlag_BoughtQuiverMedium, // ItemId_QuiverMedium
    RandoAdventureFlag_BoughtBombBagMedium, // ItemId_BombBagMedium
    RandoAdventureFlag_BoughtForceGem_43, // ItemId_ForceGem_43
    RandoAdventureFlag_BoughtForceGem_44, // ItemId_ForceGem_44
    RandoAdventureFlag_BoughtForceGem_45, // ItemId_ForceGem_45
    RandoAdventureFlag_BoughtForceGem_46, // ItemId_ForceGem_46
    RandoAdventureFlag_BoughtForceGem_47, // ItemId_ForceGem_47
    RandoAdventureFlag_BoughtForceGem_48, // ItemId_ForceGem_48
    RandoAdventureFlag_BoughtForceGem_49, // ItemId_ForceGem_49
    RandoAdventureFlag_BoughtForceGem_50, // ItemId_ForceGem_50
    RandoAdventureFlag_BoughtForceGem_51, // ItemId_ForceGem_51
    RandoAdventureFlag_BoughtForceGem_52, // ItemId_ForceGem_52
    RandoAdventureFlag_BoughtForceGem_53, // ItemId_ForceGem_53
    RandoAdventureFlag_BoughtForceGem_54, // ItemId_ForceGem_54
    RandoAdventureFlag_BoughtForceGem_55, // ItemId_ForceGem_55
    RandoAdventureFlag_BoughtForceGem_56, // ItemId_ForceGem_56
    RandoAdventureFlag_BoughtForceGem_57, // ItemId_ForceGem_57
    RandoAdventureFlag_BoughtForceGem_58, // ItemId_ForceGem_58
    RandoAdventureFlag_BoughtForceGem_59, // ItemId_ForceGem_59
    RandoAdventureFlag_BoughtForceGem_60, // ItemId_ForceGem_60
    RandoAdventureFlag_BoughtForceGem_61, // ItemId_ForceGem_61
    RandoAdventureFlag_BoughtPanFlute, // ItemId_PanFlute
    RandoAdventureFlag_BoughtStampBook, // ItemId_StampBook
    RandoAdventureFlag_BoughtLightBow, // ItemId_LightBow
    RandoAdventureFlag_BoughtLokomoSword, // ItemId_LokomoSword
    RandoAdventureFlag_BoughtTenPriceCard, // ItemId_TenPriceCard
    RandoAdventureFlag_BoughtRedPotion, // ItemId_RedPotion
    RandoAdventureFlag_BoughtPurplePotion, // ItemId_PurplePotion
    RandoAdventureFlag_BoughtYellowPotion, // ItemId_YellowPotion
    RandoAdventureFlag_BoughtDemonFossil, // ItemId_DemonFossil
    RandoAdventureFlag_BoughtStalfosSkull, // ItemId_StalfosSkull
    RandoAdventureFlag_BoughtStarFragment, // ItemId_StarFragment
    RandoAdventureFlag_BoughtBeeLarvae, // ItemId_BeeLarvae
    RandoAdventureFlag_BoughtWoodHeart, // ItemId_WoodHeart
    RandoAdventureFlag_BoughtDarkPearlLoop, // ItemId_DarkPearlLoop
    RandoAdventureFlag_BoughtWhitePearlLoop, // ItemId_WhitePearlLoop
    RandoAdventureFlag_BoughtRutoCrown, // ItemId_RutoCrown
    RandoAdventureFlag_BoughtDragonScale, // ItemId_DragonScale
    RandoAdventureFlag_BoughtPirateNecklace, // ItemId_PirateNecklace
    RandoAdventureFlag_BoughtPalaceDish, // ItemId_PalaceDish
    RandoAdventureFlag_BoughtGoronAmber, // ItemId_GoronAmber
    RandoAdventureFlag_BoughtMysticJade, // ItemId_MysticJade
    RandoAdventureFlag_BoughtAncientCoin, // ItemId_AncientCoin
    RandoAdventureFlag_BoughtPricelessStone, // ItemId_PricelessStone
    RandoAdventureFlag_BoughtRegalRing, // ItemId_RegalRing
    RandoAdventureFlag_BoughtArrowsRefill, // ItemId_ArrowsRefill
    RandoAdventureFlag_BoughtBombsRefill, // ItemId_BombsRefill
    RandoAdventureFlag_BoughtSoldOutSign, // ItemId_SoldOutSign
    RandoAdventureFlag_BoughtAncientShield, // ItemId_AncientShield
    RandoAdventureFlag_BoughtQuiverLarge, // ItemId_QuiverLarge
    RandoAdventureFlag_BoughtBombBagLarge, // ItemId_BombBagLarge
    RandoAdventureFlag_BoughtRandCommonTreasure, // ItemId_RandCommonTreasure
    RandoAdventureFlag_BoughtRandUncommonTreasure, // ItemId_RandUncommonTreasure
    RandoAdventureFlag_BoughtRandRareTreasure, // ItemId_RandRareTreasure
    RandoAdventureFlag_BoughtRandLegendaryTreasure, // ItemId_RandLegendaryTreasure
    RandoAdventureFlag_BoughtTearLight, // ItemId_TearLight
    RandoAdventureFlag_BoughtLightCompass, // ItemId_LightCompass
    RandoAdventureFlag_BoughtScrollSpinAttack, // ItemId_ScrollSpinAttack
    RandoAdventureFlag_BoughtScrollBeam, // ItemId_ScrollBeam
    RandoAdventureFlag_BoughtLinebeckLetter, // ItemId_LinebeckLetter
    RandoAdventureFlag_BoughtPanFluteSong_101, // ItemId_PanFluteSong_101
    RandoAdventureFlag_BoughtPanFluteSong_102, // ItemId_PanFluteSong_102
    RandoAdventureFlag_BoughtPanFluteSong_103, // ItemId_PanFluteSong_103
    RandoAdventureFlag_BoughtPanFluteSong_104, // ItemId_PanFluteSong_104
    RandoAdventureFlag_BoughtPanFluteSong_105, // ItemId_PanFluteSong_105
    RandoAdventureFlag_BoughtRabbitNet, // ItemId_RabbitNet
    RandoAdventureFlag_BoughtBeedleCard, // ItemId_BeedleCard
    RandoAdventureFlag_BoughtSilverCard, // ItemId_SilverCard
    RandoAdventureFlag_BoughtGoldCard, // ItemId_GoldCard
    RandoAdventureFlag_BoughtPlatinumCard, // ItemId_PlatinumCard
    RandoAdventureFlag_BoughtDiamondCard, // ItemId_DiamondCard
    RandoAdventureFlag_BoughtFreebieCard, // ItemId_FreebieCard
    RandoAdventureFlag_BoughtQuintupleCard, // ItemId_QuintupleCard
    RandoAdventureFlag_BoughtCarbenLetter, // ItemId_CarbenLetter
    RandoAdventureFlag_BoughtRecruitUniform2, // ItemId_RecruitUniform2
    RandoAdventureFlag_BoughtEngineerUniform, // ItemId_EngineerUniform

    RandoAdventureFlag_TearLight_1, // ExtraItemId_TearLight_1
    RandoAdventureFlag_TearLight_2, // ExtraItemId_TearLight_2
    RandoAdventureFlag_TearLight_3, // ExtraItemId_TearLight_3
    RandoAdventureFlag_TearLight_4, // ExtraItemId_TearLight_4
    RandoAdventureFlag_TearLight_5, // ExtraItemId_TearLight_5
    RandoAdventureFlag_NormalKey_2, // ExtraItemId_NormalKey_2
    RandoAdventureFlag_NormalKey_4, // ExtraItemId_NormalKey_4
    RandoAdventureFlag_NormalKey_5, // ExtraItemId_NormalKey_5
    RandoAdventureFlag_NormalKey_6, // ExtraItemId_NormalKey_6
    RandoAdventureFlag_NormalKey_Tunnel, // ExtraItemId_NormalKey_Tunnel
    RandoAdventureFlag_NormalKey_Wooded, // ExtraItemId_NormalKey_Wooded
    RandoAdventureFlag_NormalKey_Blizzard, // ExtraItemId_NormalKey_Blizzard
    RandoAdventureFlag_NormalKey_Marine, // ExtraItemId_NormalKey_Marine
    RandoAdventureFlag_NormalKey_Mountain, // ExtraItemId_NormalKey_Mountain
    RandoAdventureFlag_NormalKey_Desert, // ExtraItemId_NormalKey_Desert
};
