#!/usr/bin/env python3

import csv
import yaml

from pathlib import Path


actor_ids = [
    "AJAI",
    "AJBS",
    "AJCR",
    "AJEM",
    "AJET",
    "AJMN",
    "AJNP",
    "AJSP",
    "AJTM",
    "ALEV",
    "AROW",
    "ASBA",
    "ASYU",
    "ATTG",
    "BAEY",
    "BAFO",
    "BANI",
    "BAPH",
    "BBLE",
    "BDBA",
    "BDEA",
    "BDEM",
    "BDGA",
    "BDLB",
    "BEEE",
    "BEEH",
    "BFFN",
    "BGOK",
    "BKST",
    "BLBL",
    "BLBR",
    "BLJF",
    "BLON",
    "BLST",
    "BMHN",
    "BMOC",
    "BOMB",
    "BPAP",
    "BPBS",
    "BROW",
    "BSFC",
    "BSKM",
    "BSTG",
    "BTIR",
    "CAGE",
    "CAMA",
    "CAMB",
    "CAMS",
    "CAMY",
    "CANS",
    "CASE",
    "CASL",
    "CAST",
    "CAWA",
    "CAWB",
    "CHUC",
    "CLBT",
    "CLLT",
    "CLZN",
    "CNBL",
    "COMM",
    "CRCH",
    "CRFP",
    "CRFT",
    "CROW",
    "CTFS",
    "DGPC",
    "DKCB",
    "DKCL",
    "DKTR",
    "DLPN",
    "DLTG",
    "DMCH",
    "DMEQ",
    "DMET",
    "DMFR",
    "DMFT",
    "DMGM",
    "DMGN",
    "DMMM",
    "DMMS",
    "DMMT",
    "DMPK",
    "DMPS",
    "DMSS",
    "DMST",
    "DMT2",
    "DMTR",
    "DMWS",
    "DMWT",
    "DMZS",
    "DSBB",
    "DSBH",
    "DSBN",
    "DSDS",
    "DSFR",
    "DSSN",
    "DSVC",
    "DSWT",
    "E3GL",
    "E3LV",
    "E3ST",
    "E3TT",
    "EFIK",
    "EFOC",
    "EFR2",
    "EFR3",
    "EFRI",
    "EFRL",
    "EFRP",
    "EFSB",
    "EFSC",
    "EFW2",
    "EFW3",
    "EFWI",
    "EFWL",
    "EFWV",
    "ELVT",
    "ENGE",
    "EVCH",
    "EVIC",
    "EWHI",
    "FBBF",
    "FBBH",
    "FBCH",
    "FBRD",
    "FBRG",
    "FBSC",
    "FCHL",
    "FDKY",
    "FIBB",
    "FIFI",
    "FIMA",
    "FIML",
    "FIRB",
    "FKTR",
    "FLCT",
    "FLDK",
    "FLEN",
    "FMAS",
    "FMLS",
    "FOFA",
    "FOMA",
    "FOMB",
    "FOMC",
    "FOMD",
    "FOMR",
    "FOMS",
    "FOMY",
    "FOPD",
    "FRBS",
    "FRTN",
    "FSIR",
    "FSSF",
    "FSST",
    "FTRN",
    "GHOS",
    "GOCA",
    "GOCB",
    "GOCP",
    "GOKI",
    "GORK",
    "GORM",
    "GORP",
    "GORS",
    "GORY",
    "GOVT",
    "GRCF",
    "GRCM",
    "GTTG",
    "GYAM",
    "HAMN",
    "HELA",
    "HERT",
    "HLMG",
    "HYSW",
    "IBBA",
    "IBSP",
    "ICBA",
    "ICBB",
    "ICBS",
    "ITBM",
    "ITSC",
    "ITTD",
    "ITWP",
    "IWTS",
    "JOLN",
    "KETH",
    "KEYB",
    "KEYN",
    "KEYT",
    "KGDB",
    "KGDN",
    "KIMA",
    "KIMB",
    "KLTR",
    "KMOH",
    "KMOS",
    "KMSO",
    "KOAT",
    "KOCH",
    "KOKO",
    "KOTA",
    "KURI",
    "L2MT",
    "L2V1",
    "L2V2",
    "LAVA",
    "LBCK",
    "LBRC",
    "LIKE",
    "LIRA",
    "LOCK",
    "LVBD",
    "LVOF",
    "LZET",
    "MABC",
    "MABL",
    "MAFI",
    "MAGR",
    "MARG",
    "MATR",
    "MBCC",
    "MDYG",
    "MGAJ",
    "MIFR",
    "MKUR",
    "MLCK",
    "MNCB",
    "MOCT",
    "MRD2",
    "MRDA",
    "MRDL",
    "MRDO",
    "MTFB",
    "MTFL",
    "MTWP",
    "MZCT",
    "NAVI",
    "NCCA",
    "NCCB",
    "NCCS",
    "NCMB",
    "NCWA",
    "NFSP",
    "NICO",
    "NITF",
    "NLTR",
    "NORE",
    "NPWC",
    "NSHD",
    "NSSW",
    "NSTN",
    "NTTZ",
    "NTUB",
    "OBPC",
    "OCGS",
    "OCTA",
    "OCTG",
    "OCTS",
    "OCTW",
    "OCWS",
    "OFSW",
    "OLDM",
    "OLDS",
    "PASS",
    "PBK2",
    "PBSP",
    "PCTG",
    "PHEY",
    "PHTM",
    "PLSR",
    "PMST",
    "PMTB",
    "PMTC",
    "PMTD",
    "POST",
    "PPPM",
    "PRPL",
    "PRPP",
    "PRSP",
    "PSBK",
    "PSBL",
    "PSBS",
    "PSEM",
    "PSNP",
    "PSWB",
    "PTMN",
    "QKSD",
    "QKTG",
    "RAT0",
    "RB1F",
    "RB1T",
    "RBD2",
    "RBDS",
    "RBFR",
    "RBL1",
    "RBL2",
    "RBLS",
    "RBNT",
    "RBRP",
    "RBRT",
    "RBSN",
    "RBVC",
    "RBWS",
    "RBWT",
    "RCFO",
    "RCHU",
    "RCMS",
    "RCSG",
    "RLST",
    "RMA0",
    "RMA1",
    "RMA2",
    "RMA3",
    "RMAJ",
    "RMBC",
    "RMBD",
    "RMC0",
    "RMC1",
    "RMC2",
    "RMC3",
    "RMC4",
    "RMC5",
    "RMC6",
    "RMDO",
    "RMDS",
    "RMF0",
    "RMF1",
    "RMFK",
    "RML0",
    "RML1",
    "RML2",
    "RML3",
    "RMLF",
    "RMM0",
    "RMM1",
    "RMM2",
    "RMM3",
    "RMM4",
    "RMS0",
    "RMS1",
    "RMS2",
    "RMS3",
    "RMS4",
    "RMS5",
    "RMSD",
    "RMSF",
    "RMSS",
    "RMST",
    "RMSV",
    "RMSW",
    "RMT0",
    "RMT1",
    "RMT2",
    "RMT3",
    "RMT4",
    "RMTB",
    "RMTE",
    "RMTG",
    "RMTR",
    "RMTZ",
    "RMV0",
    "RMV1",
    "RMVD",
    "RMVF",
    "RMVS",
    "RMVT",
    "RMVV",
    "RMVW",
    "RMW0",
    "RMW1",
    "RNTN",
    "ROCK",
    "RPMT",
    "RUPE",
    "RYAW",
    "SCCN",
    "SEAT",
    "SEFS",
    "SGMG",
    "SHDL",
    "SHIT",
    "SIRO",
    "SIRS",
    "SKDO",
    "SMCT",
    "SNMA",
    "SNMB",
    "SNOW",
    "SNST",
    "SOGB",
    "SOGC",
    "SOLB",
    "SOLC",
    "SOLD",
    "SOLF",
    "SOLG",
    "SOLT",
    "SPAR",
    "SPBM",
    "SPDR",
    "SPID",
    "SPTG",
    "SPTR",
    "SPTT",
    "SRNM",
    "SRSL",
    "SRST",
    "SSFC",
    "STCT",
    "STFB",
    "STFH",
    "STLF",
    "STLW",
    "STTG",
    "STWH",
    "SWBM",
    "SWCH",
    "SWDS",
    "SWHI",
    "SWOB",
    "SWON",
    "SWTM",
    "SYDE",
    "SYDL",
    "SYDS",
    "SYFI",
    "SYFO",
    "SYIL",
    "SYIS",
    "SYOL",
    "SYOS",
    "SYRN",
    "SYSL",
    "SYSN",
    "SYSS",
    "SYWA",
    "SYWL",
    "SYWS",
    "SZKL",
    "SZKU",
    "SZRD",
    "TBRD",
    "TCAM",
    "TCOW",
    "TDKT",
    "TEHT",
    "TERY",
    "TEVT",
    "TFAT",
    "TGTZ",
    "THER",
    "TKYT",
    "TLKT",
    "TMNA",
    "TMNC",
    "TMNP",
    "TPDO",
    "TRAP",
    "TRBC",
    "TRCB",
    "TRER",
    "TRIC",
    "TRLY",
    "TRRL",
    "TRSG",
    "TRSP",
    "TRTT",
    "TRUP",
    "TSCN",
    "TSLB",
    "TSMT",
    "TTET",
    "TTFT",
    "TTKB",
    "TTUT",
    "TUTO",
    "TVLR",
    "VCCH",
    "VCFT",
    "VLCR",
    "VOLV",
    "VRGN",
    "WAMA",
    "WAWA",
    "WAWB",
    "WAWC",
    "WAWS",
    "WAWY",
    "WBEF",
    "WBN2",
    "WBPS",
    "WBTN",
    "WCAS",
    "WDBA",
    "WDRD",
    "WHMA",
    "WIDR",
    "WIDT",
    "WKTR",
    "WPBD",
    "WPCH",
    "WPCL",
    "WTBS",
    "WTH2",
    "WTH3",
    "WTTH",
    "WWFS",
    "YKAP",
    "YKCP",
    "YKEP",
    "YUKI",
    "YUKY",
    "YWIS",
    "ZELD",
    "ZLBB",
    "ZLBS",
    "ZLSL",
    "ZLSN",
    "ZLSS",
    "ZSRS",
    "ZSTG",
]

mapobj_ids = [
    "ARWL",
    "BAPL",
    "BBFL",
    "BFFL",
    "BFSP",
    "BLCC",
    "BLCE",
    "BLCK",
    "BLCM",
    "BLCT",
    "BLHL",
    "BLRB",
    "BLSR",
    "BMFL",
    "BOGN",
    "BREX",
    "BRGL",
    "BRGS",
    "BRGW",
    "CLMN",
    "CRWL",
    "CSTL",
    "CTPT",
    "DFNC",
    "DOPA",
    "DRBK",
    "DRBR",
    "DRCK",
    "DRDS",
    "DRGN",
    "DRHS",
    "DRKY",
    "DRMC",
    "DRRS",
    "DRSN",
    "DRST",
    "DRSW",
    "DRTC",
    "DRTK",
    "DRTW",
    "DRTY",
    "DRVC",
    "DRVT",
    "EBRD",
    "EFRF",
    "EFRS",
    "ETDD",
    "ETDK",
    "ETET",
    "ETFD",
    "ETMW",
    "ETNL",
    "ETNM",
    "ETNS",
    "ETSD",
    "ETSW",
    "ETTV",
    "ETUS",
    "ETYG",
    "EXCT",
    "EXHS",
    "EXIT",
    "EXTR",
    "FLSP",
    "FNCE",
    "FRAI",
    "FRSH",
    "FRWL",
    "FSCT",
    "FSFR",
    "FSFS",
    "FSPS",
    "FSSN",
    "FSSV",
    "FSTA",
    "FSVC",
    "FSWT",
    "GATE",
    "GBDR",
    "GELG",
    "GRSG",
    "GRSS",
    "GRSV",
    "GSST",
    "GTAT",
    "GTRB",
    "GTRK",
    "GTSN",
    "GTTN",
    "HOF0",
    "HOF1",
    "HOL0",
    "HOL1",
    "HOL2",
    "HOLB",
    "HOSB",
    "HOSO",
    "HOST",
    "HOUS",
    "HOW0",
    "HOW1",
    "ICEB",
    "ICGR",
    "ITFL",
    "KNBN",
    "LEVN",
    "LEVS",
    "LTRW",
    "LVCM",
    "LVVT",
    "MBBS",
    "MBRG",
    "MLVC",
    "MSCL",
    "MTFS",
    "MTGT",
    "MTIC",
    "MTIR",
    "MTJR",
    "MTOR",
    "MTWD",
    "MTWR",
    "MZFE",
    "MZFX",
    "MZTR",
    "NPST",
    "PLCT",
    "PLFA",
    "PLFM",
    "PLFR",
    "PLV2",
    "PRSH",
    "PTFL",
    "RBBL",
    "RBMR",
    "RBRC",
    "RBSR",
    "RCFL",
    "RDSD",
    "RKAG",
    "RLPT",
    "RLSG",
    "RNBO",
    "RPFL",
    "SAND",
    "SBDE",
    "SHWB",
    "SKBN",
    "SKDI",
    "SPTB",
    "STAL",
    "STAT",
    "STDE",
    "STDS",
    "STIR",
    "STNE",
    "STSD",
    "STSF",
    "STSH",
    "STSP",
    "STSS",
    "STSV",
    "STTR",
    "SWBR",
    "SWCB",
    "SWCR",
    "SWEY",
    "SWFS",
    "SWHT",
    "SWRA",
    "SWRB",
    "SWST",
    "SWSW",
    "SWWN",
    "TATZ",
    "TBSD",
    "TBSF",
    "TBSS",
    "TCBT",
    "TDBP",
    "TDBR",
    "TDDR",
    "THAW",
    "TMDE",
    "TMFR",
    "TMLV",
    "TMSB",
    "TMSN",
    "TMWT",
    "TRBL",
    "TRBM",
    "TRBR",
    "TRCC",
    "TRDA",
    "TRDR",
    "TRDT",
    "TRED",
    "TREE",
    "TREN",
    "TRES",
    "TRET",
    "TREW",
    "TRFI",
    "TRFO",
    "TRFS",
    "TRFV",
    "TRGM",
    "TRGW",
    "TRH0",
    "TRH1",
    "TRH2",
    "TRH3",
    "TRLD",
    "TRLN",
    "TRLS",
    "TRLW",
    "TRMA",
    "TRMR",
    "TRPI",
    "TRPT",
    "TRRA",
    "TRRC",
    "TRRD",
    "TRRS",
    "TRRW",
    "TRSA",
    "TRSD",
    "TRSH",
    "TRSR",
    "TRSS",
    "TRST",
    "TRSW",
    "TRTF",
    "TRTS",
    "TRWA",
    "TRWS",
    "TSGM",
    "TSUB",
    "TWGS",
    "TWPC",
    "TWPG",
    "WDST",
    "WHSW",
    "WLMP",
    "WLMS",
    "WPHL",
]


# from https://github.com/yaml/pyyaml/issues/127#issuecomment-525800484
class MyDumper(yaml.SafeDumper):
    # HACK: insert blank lines between top-level objects
    # inspired by https://stackoverflow.com/a/44284819/3786245
    def write_line_break(self, data=None):
        super().write_line_break(data)

        if len(self.indents) == 1:
            super().write_line_break()


if __name__ == "__main__":
    csv_file = Path("rando/data/location_table.csv").resolve()
    assert csv_file.exists()

    yaml_file = {}
    yaml_out = Path("rando/data/location_table.yaml").resolve()

    yaml_file_test = {}
    yaml_test_out = Path("rando/test/test_world.yaml").resolve()

    with csv_file.open("r") as file:
        csv_data = csv.reader(file)

        for i, entry in enumerate(csv_data):
            if i == 0:
                continue
            
            name, scene, room, id, x, y = tuple(entry)

            if ".bmg" in id:
                split = id.split(" @ ")

                yaml_file[name] = {
                    "is_bmg": True,
                    "bmg": split[0],
                    "scene": scene,
                    "room_index": int(room),
                    "offsets": {
                        "English": split[1].split(", ")
                    },
                }
            elif "Cutscene" in id:
                yaml_file[name] = {
                    "is_cs": True,
                    "vanilla_item_flag": id.split(": ")[-1],
                    "scene": scene,
                    "room_index": int(room),
                }
            elif len(id) > 0 and len(x) > 0 and len(y) > 0:
                if id in actor_ids:
                    is_actor = True
                elif id in mapobj_ids:
                    is_actor = False
                else:
                    raise ValueError(f"unexpected id: {id}")

                if is_actor:
                    id_hash = f"{id}_0x{int(x):04X}_0x{int(y):04X}"
                else:
                    id_hash = f"{id}_0x{int(x):02X}_0x{int(y):02X}"

                yaml_file[name] = {
                    "scene": scene,
                    "room_index": int(room),
                    "id_hash": id_hash,
                }

                if is_actor:
                    yaml_file[name]["is_actor"] = True
                else:
                    yaml_file[name]["is_mapobj"] = True

    with yaml_out.open("w") as file:
        yaml.dump(yaml_file, file, Dumper=MyDumper)

    world = {}
    for loc, data in yaml_file.items():
        scene = data["scene"]
        room_index = data["room_index"]
        node_name = f"node_{scene}"

        if node_name not in world:
            world[node_name] = {
                "scene": scene,
                "room_index": room_index,
                "locations": {}
            }
        
        if loc not in world[node_name]["locations"]:
            world[node_name]["locations"][loc] = "True"

    with yaml_test_out.open("w") as file:
        yaml.dump(world, file, Dumper=MyDumper)
