# Form implementation generated from reading ui file 'ui/preset_save.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PresetSave(object):
    def setupUi(self, PresetSave):
        PresetSave.setObjectName("PresetSave")
        PresetSave.resize(400, 108)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=PresetSave)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 98))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_box = QtWidgets.QDialogButtonBox(parent=self.gridLayoutWidget)
        self.btn_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btn_box.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel | QtWidgets.QDialogButtonBox.StandardButton.Ok
        )
        self.btn_box.setObjectName("btn_box")
        self.gridLayout.addWidget(self.btn_box, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 1, 1, 1)

        self.retranslateUi(PresetSave)
        QtCore.QMetaObject.connectSlotsByName(PresetSave)

    def retranslateUi(self, PresetSave):
        _translate = QtCore.QCoreApplication.translate
        PresetSave.setWindowTitle(_translate("PresetSave", "ST Randomizer - Save Preset"))
        self.label.setText(_translate("PresetSave", "Preset Name"))
